/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ysmms;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author GHAB
 */
public class mainpage extends javax.swing.JFrame {

    /**
     * Creates new form mainpage
     */
    public mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPane = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        username = new javax.swing.JLabel();
        passsword = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        adminHome = new javax.swing.JPanel();
        welcomeAdmin = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        addCustomer = new javax.swing.JButton();
        removeCustomer = new javax.swing.JButton();
        editProfile = new javax.swing.JButton();
        logoutAdmin = new javax.swing.JButton();
        viewProduct = new javax.swing.JButton();
        ownerhome = new javax.swing.JPanel();
        welcomeOwner = new javax.swing.JLabel();
        statusOwner = new javax.swing.JLabel();
        addEmployee = new javax.swing.JButton();
        removeEmployee = new javax.swing.JButton();
        editProfileOwner = new javax.swing.JButton();
        logoutOwner = new javax.swing.JButton();
        viewProductOwner = new javax.swing.JButton();
        removeProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        customerHome = new javax.swing.JPanel();
        welcomeCustomer = new javax.swing.JLabel();
        statusCustomer = new javax.swing.JLabel();
        editCustomer = new javax.swing.JButton();
        logoutCustomer = new javax.swing.JButton();
        viewProductCustomer = new javax.swing.JButton();
        viewProductPane = new javax.swing.JPanel();
        welcomeProducts = new javax.swing.JLabel();
        productsList = new javax.swing.JComboBox<>();
        viewComment = new javax.swing.JButton();
        addToCart = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        buyProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        wishList = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        cashierHome = new javax.swing.JPanel();
        welcomeCashier = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        createBill1 = new javax.swing.JButton();
        viewProfile = new javax.swing.JButton();
        viewProductPaneAdmin = new javax.swing.JPanel();
        welcomeProducts1 = new javax.swing.JLabel();
        productsListAdmin = new javax.swing.JComboBox<>();
        viewComment1 = new javax.swing.JButton();
        detail1 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        allPane.setLayout(new java.awt.CardLayout());

        login.setName(""); // NOI18N
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setText("welcome to yaleself supermarket management system");
        login.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 440, 40));
        login.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 140, -1));

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        login.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 140, -1));

        username.setText("username");
        login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        passsword.setText("password");
        login.add(passsword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        loginbtn.setText("login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        login.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jButton1.setText("contact us");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        allPane.add(login, "login");

        adminHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeAdmin.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeAdmin.setText("Yaleself supermarket management system");
        adminHome.add(welcomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        status.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        status.setText("you logged in as admin");
        adminHome.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        addCustomer.setText("add customer");
        adminHome.add(addCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        removeCustomer.setText("remove customer");
        adminHome.add(removeCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));

        editProfile.setText("edit profile");
        adminHome.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));

        logoutAdmin.setText("logout");
        logoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdminActionPerformed(evt);
            }
        });
        adminHome.add(logoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        viewProduct.setText("view product");
        viewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductActionPerformed(evt);
            }
        });
        adminHome.add(viewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 120, -1));

        allPane.add(adminHome, "adminHome");

        ownerhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeOwner.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeOwner.setText("Yaleself supermarket management system");
        ownerhome.add(welcomeOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        statusOwner.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        statusOwner.setText("you logged in as owner");
        ownerhome.add(statusOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        addEmployee.setText("add employee");
        ownerhome.add(addEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        removeEmployee.setText("remove emmployee");
        ownerhome.add(removeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        editProfileOwner.setText("edit profile");
        ownerhome.add(editProfileOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 120, -1));

        logoutOwner.setText("logout");
        logoutOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutOwnerActionPerformed(evt);
            }
        });
        ownerhome.add(logoutOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        viewProductOwner.setText("view product");
        ownerhome.add(viewProductOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 130, -1));

        removeProduct.setText("remove product");
        ownerhome.add(removeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, -1));

        addProduct.setText("add product");
        ownerhome.add(addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 130, -1));

        allPane.add(ownerhome, "ownerHome");

        customerHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeCustomer.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeCustomer.setText("Yaleself supermarket management system");
        customerHome.add(welcomeCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        statusCustomer.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        statusCustomer.setText("you logged in as customer");
        customerHome.add(statusCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        editCustomer.setText("edit profile");
        customerHome.add(editCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 120, -1));

        logoutCustomer.setText("logout");
        logoutCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutCustomerActionPerformed(evt);
            }
        });
        customerHome.add(logoutCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        viewProductCustomer.setText("view product");
        viewProductCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductCustomerActionPerformed(evt);
            }
        });
        customerHome.add(viewProductCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, -1));

        allPane.add(customerHome, "customerHome");

        viewProductPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeProducts.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeProducts.setText("Yaleself supermarket management system");
        viewProductPane.add(welcomeProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        productsList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sunchips", "pen" }));
        productsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsListActionPerformed(evt);
            }
        });
        viewProductPane.add(productsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, -1));

        viewComment.setText("view comment");
        viewComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCommentActionPerformed(evt);
            }
        });
        viewProductPane.add(viewComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        addToCart.setText("add to wishlist");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        viewProductPane.add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        detail.setText("detail");
        viewProductPane.add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        buyProduct.setText("buy product");
        buyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyProductActionPerformed(evt);
            }
        });
        viewProductPane.add(buyProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        wishList.setColumns(20);
        wishList.setRows(5);
        jScrollPane1.setViewportView(wishList);

        viewProductPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 180, 380, 130));

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        viewProductPane.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 80, -1));

        allPane.add(viewProductPane, "viewProductPane");

        cashierHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeCashier.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeCashier.setText("Yaleself supermarket management system");
        cashierHome.add(welcomeCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        cashierHome.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        createBill1.setText("create bill");
        cashierHome.add(createBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        viewProfile.setText("view profile");
        cashierHome.add(viewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        allPane.add(cashierHome, "cashierHome");

        viewProductPaneAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeProducts1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        welcomeProducts1.setText("Yaleself supermarket management system");
        viewProductPaneAdmin.add(welcomeProducts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, -1, -1));

        productsListAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sunchips", "pen" }));
        productsListAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsListAdminActionPerformed(evt);
            }
        });
        viewProductPaneAdmin.add(productsListAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, -1));

        viewComment1.setText("view comment");
        viewComment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComment1ActionPerformed(evt);
            }
        });
        viewProductPaneAdmin.add(viewComment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        detail1.setText("detail");
        viewProductPaneAdmin.add(detail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        back1.setText("back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        viewProductPaneAdmin.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 80, -1));

        allPane.add(viewProductPaneAdmin, "card8");

        getContentPane().add(allPane, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        if (userField.getText().equalsIgnoreCase( "owner" )&& passField.getText().equalsIgnoreCase("owner")){
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "ownerHome");}
        else if (userField.getText().equalsIgnoreCase( "admin" )&& passField.getText().equalsIgnoreCase("admin")){
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "adminHome");}
        else if (userField.getText().equalsIgnoreCase( "customer" )&& passField.getText().equalsIgnoreCase("customer")){
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "customerHome");}
        else if (userField.getText().equalsIgnoreCase( "cashier" )&& passField.getText().equalsIgnoreCase("cashier")){
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "cashierHome");}
        else{
            JOptionPane.showMessageDialog(null,"No user with this data please check your input!");
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void productsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsListActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productsListActionPerformed

    private void viewCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCommentActionPerformed

    private void logoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdminActionPerformed
        // TODO add your handling code here:
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "login");
    }//GEN-LAST:event_logoutAdminActionPerformed

    private void viewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductActionPerformed
        // TODO add your handling code here:
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "viewProductPaneAdmin");
    }//GEN-LAST:event_viewProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"contact us on:\n\ttelegram: +251 111111\n\tphone: 251 0000");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutOwnerActionPerformed
        // TODO add your handling code here:
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "login");
    }//GEN-LAST:event_logoutOwnerActionPerformed

    private void logoutCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutCustomerActionPerformed
        // TODO add your handling code here:
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "login");
    }//GEN-LAST:event_logoutCustomerActionPerformed

    private void buyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyProductActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "login");
    }//GEN-LAST:event_logoutActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
        wishList.setText(wishList.getText()+"\n"+productsList.getSelectedItem().toString());
        wishList.setEditable(false);
    }//GEN-LAST:event_addToCartActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "customerHome");
    }//GEN-LAST:event_backActionPerformed

    private void viewProductCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductCustomerActionPerformed
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "viewProductPane");
    }//GEN-LAST:event_viewProductCustomerActionPerformed

    private void productsListAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsListAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsListAdminActionPerformed

    private void viewComment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewComment1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        CardLayout active = (CardLayout)(allPane.getLayout());
        active.show(allPane, "adminHome");
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomer;
    private javax.swing.JButton addEmployee;
    private javax.swing.JButton addProduct;
    public javax.swing.JButton addToCart;
    private javax.swing.JPanel adminHome;
    public javax.swing.JPanel allPane;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    public javax.swing.JButton buyProduct;
    private javax.swing.JPanel cashierHome;
    private javax.swing.JButton createBill1;
    private javax.swing.JPanel customerHome;
    public javax.swing.JButton detail;
    public javax.swing.JButton detail1;
    private javax.swing.JButton editCustomer;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton editProfileOwner;
    private javax.swing.JButton jButton1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton logout;
    private javax.swing.JButton logoutAdmin;
    private javax.swing.JButton logoutCustomer;
    private javax.swing.JButton logoutOwner;
    private javax.swing.JPanel ownerhome;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passsword;
    public javax.swing.JComboBox<String> productsList;
    public javax.swing.JComboBox<String> productsListAdmin;
    private javax.swing.JButton removeCustomer;
    private javax.swing.JButton removeEmployee;
    private javax.swing.JButton removeProduct;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusCustomer;
    private javax.swing.JLabel statusOwner;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel username;
    public javax.swing.JButton viewComment;
    public javax.swing.JButton viewComment1;
    private javax.swing.JButton viewProduct;
    private javax.swing.JButton viewProductCustomer;
    private javax.swing.JButton viewProductOwner;
    private javax.swing.JPanel viewProductPane;
    private javax.swing.JPanel viewProductPaneAdmin;
    private javax.swing.JButton viewProfile;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcomeAdmin;
    private javax.swing.JLabel welcomeCashier;
    private javax.swing.JLabel welcomeCustomer;
    private javax.swing.JLabel welcomeOwner;
    private javax.swing.JLabel welcomeProducts;
    private javax.swing.JLabel welcomeProducts1;
    public javax.swing.JTextArea wishList;
    // End of variables declaration//GEN-END:variables
}
